call DEMO.DEMO.RETURN_MTA_NEARBY('40.583957672', '-74.16104126');

describe table icymta;

 SELECT VEHICLEREF as bus, destinationname, 
         expectedarrivaltime,
         EXPECTEDDEPARTURETIME, stoppointname, bearing,HAVERSINE( VEHICLELOCATIONLATITUDE, VEHICLELOCATIONLONGITUDE, '40.583957672',	
         '-74.16104126' ) as distance, 
         (ST_DISTANCE(ST_MAKEPOINT(VEHICLELOCATIONLATITUDE,VEHICLELOCATIONLONGITUDE), ST_MAKEPOINT('40.583957672','-74.16104126'))/1609) as distanceinmiles,
         distancefromstop,SITUATIONSIMPLEREF1 as IncidentDescription, 
      recordedattime, ESTIMATEDPASSENGERCOUNT, 
      ESTIMATEDPASSENGERCAPACITY, 
      arrivalproximitytext,
      NUMBEROFSTOPSAWAY, 
      TS 
  FROM icymta
  WHERE DISTANCEFROMSTOP > 0
  ORDER BY distance ASC;
  

CREATE OR REPLACE PROCEDURE DEMO.DEMO.RETURN_MTA_NEARBY("YOURLATITUDE" VARCHAR, "YOURLONGITUDE" VARCHAR)
RETURNS TABLE ("BUS" VARCHAR, "destinationname" VARCHAR, "EXPECTEDARRIVALTIME" VARCHAR, "EXPECTEDDEPARTURETIME" VARCHAR, "STOPPOINTNAME" VARCHAR, "BEARING" FLOAT, "DISTANCE" FLOAT, "DISTANCEINMILES" FLOAT, "DISTANCEFROMSTOP" VARCHAR, "INCIDENTDESCRIPTION" VARCHAR, "RECORDEDATTIME" VARCHAR, "ESTIMATEDPASSENGERCOUNT" VARCHAR, "ESTIMATEDPASSENGERCAPACITY" VARCHAR, "ARRIVALPROXIMITYTEXT" VARCHAR, "NUMBEROFSTOPSAWAY" VARCHAR, "TS" TIMESTAMP_NTZ(6))
LANGUAGE SQL
EXECUTE AS OWNER
AS 'DECLARE
  res RESULTSET;
BEGIN
  res := ( SELECT VEHICLEREF as bus, destinationname, 
         expectedarrivaltime,
         EXPECTEDDEPARTURETIME, stoppointname, bearing,HAVERSINE( VEHICLELOCATIONLATITUDE, VEHICLELOCATIONLONGITUDE, :YOURLATITUDE,	
         :YOURLONGITUDE ) as distance, 
         (ST_DISTANCE(ST_MAKEPOINT(VEHICLELOCATIONLATITUDE,VEHICLELOCATIONLONGITUDE), ST_MAKEPOINT(:YOURLATITUDE,:YOURLONGITUDE))/1609) as distanceinmiles,
         distancefromstop,SITUATIONSIMPLEREF1 as IncidentDescription, 
      recordedattime, ESTIMATEDPASSENGERCOUNT, 
      ESTIMATEDPASSENGERCAPACITY, 
      arrivalproximitytext,
      NUMBEROFSTOPSAWAY, 
      TS 
  FROM icymta
  WHERE DISTANCEFROMSTOP > 0
  ORDER BY distance ASC);
  RETURN TABLE(res);
END';
